name: Run Angular Code

on: [push]

jobs:
  run-angular:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build 

    - name: Run project
      run: npm run start
